server:
  port: 9000
spring:
  application:
    name: mianshiya

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/msy
    password: root
    username: root
  redis:
    host: localhost
    port: 6379
    password: liason


jwt:
  token:
    # 过期时间 秒
    time-out: 604800
    # 缓存 命名前缀
    cache-name: mianshiya:token
    # token 前缀
    prefix: Bearer
    header: Authorization
    # 续期检查范围。 token有效期小于detect时，续期token 单位 秒
    detect: 10800
    # 续期时间为 7天 单位秒
    renew: 604800
    base64Secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=